version: "3.0"
services:
  # userInfoManager:
  #   build:
  #     context: user-info-manager
  #   container_name: userInfoManager
  #   ports:
  #   environment:
  #   depends on:
  #     - broker
  #     - zookeeper
  #     - keycloak
  #   restart: unless-stopped
  #   networks:
  #     - private
  #     - public
  
  # keycloak:
  #   image: quay.io/keycloak/keycloak:21.1.0
  #   container_name: keycloak
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #   ports:
  #     - "8080:8080"
  #   command: start-dev

  keycloak-ready:
    image: gmitis/keycloak:latest
    container_name: keycloak-ready
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev 
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

networks:
  private:
  public:

# docker tag local-image:tagname new-repo:tagname
# docker push new-repo:tagname