app_container_name: "$saas_APP_CONTAINER_NAME"
app_port: "$saas_APP_PORT"

azure_conn_str: "$saas_AZURE_CONN_STR"
azure_container_name: "$saas_AZURE_CONTAINER_NAME"

kafka_host: "$saas_KAFKA_HOST"
kafka_port: "$saas_KAFKA_PORT"

keycloak_host: "$saas_KEYCLOAK_HOST"
keycloak_port: "$saas_KEYCLOAK_PORT"
keycloak_realm_name: "$saas_KEYCLOAK_REALM_NAME"
keycloak_client_id: "$saas_KEYCLOAK_CLIENT_ID"
keycloak_client_secret_key: "$saas_KEYCLOAK_CLIENT_SECRET_KEY"