KEYCLOAK:
    SERVER_URL: http://localhost:8080/
    REALM: my-charts
    BAR_LABEL_PLOT:
        CLIENT_ID: bar-label-plot-ms
        CLIENT_SECRET: 7jBjchpXMpTO954LayY07noSs7SaL90a
    SIMPLE_PLOT:
        CLIENT_ID: simple-plot-ms
        CLIENT_SECRET: IvaLZ4EtgXzHIMYGCdOvMZr8s6X0zA7Z
    # BAR_LABEL_PLOT:
    # SCATTER_PLOT:

FRONTEND:
    SERVER_URL: http://localhost:3000

PLOT:
    TYPES: bar_label_plot,scatter_plot,simple_plot
    FORMATS: html,jpeg,png,svg